name: pogogen
author: Joel Trottier-Hebert <iamquebecois@gmail.com>
homepage: https://github.com/Pacane/pogogen
version: 0.2.0
description: A console application used to generate multiple configuration files for [PokemonGo-Bot](https://github.com/PokemonGoF/PokemonGo-Bot/).
dependencies:
  path: '>=1.3.9 <2.0.0'
  test: '>=0.12.15+1 <0.13.0'
  unscripted: '>=0.6.2 <0.7.0'
executables:
  pogogen:
